[package]
name = "AnomalyLauncher"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = {version = "0.27.2", features = ["glow", "default_fonts"], default-features = false}
rfd = { version = "0.14.1", default-features = false }
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
image = "0.25.1"

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = false

[build-dependencies]
winresource = "0.1.17"
